### ISSUE TITLE
ProjectionInterface changes

### ISSUE THREAD

**Issue by graste** [daikon-cqrs/read-model#1]
I would suggest:

- that we get rid of the AggregateRevision and AggregateIdentifier – we might put them into a separate interface if we need the functionality for some default projectors
- that we can think about using interop to/fromNative here as well?

**Comment by MrHash** [comment]
`ProjectionInterface` specifies `string` and `int` for the return types. Need to have some way to get the reference id right?

**Comment by graste** [comment]
Can't we use `AggregateRevision` and `AggregateIdentifierInterface` as defined in event-sourcing.

**Comment by MrHash** [comment]
The interop part is done. As for the other suggestion, will look into it a bit more.

**Comment by MrHash** [comment]
e52d2b7e04cffc2d4b936955e9803a6a81b26cc9 done!

AggregateId and AggregateRevision are now value objects and the ValueObjectInterface has been moved to interop lib to avoid entity dependency in event-sourcing lib
